file = open("student1(Fatima).txt", "rb")
content = file.read()
print(content)
file.close()
file = open("student1(umair).txt", "rb")
content = file.read()
print(content)
file.close()
file = open("student3(Aroosh).txt", "rb")
content = file.read()
print(content)
file.close()
file = open("student4(ayesha).txt", "rb")
content = file.read()
print(content)
file.close()
file = open("student5(zoy).txt", "rb")
content = file.read()
print(content)
file.close()
file = open("student6(bia).txt", "rb")
content = file.read()
print(content)
file.close()